In [4]:
import sys 
import os 
sys.path.insert(0, os.path.dirname(os.getcwd()))

from utils import get_connection
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import pickle 
from tqdm import tqdm

In [5]:
con = get_connection()


# tmp_needs_occasion_mapping
# - occasion_cn
# - needs_cn
# - where_en
# - who_cn


df = pd.read_sql("select distinct id ,content,  occasion_cn, needs_cn,  where_en ,who_cn from preprocessed_post_cls.tmp_needs_occasion_mapping",  con)

connecting to rm-uf6lfxk83h7onjmwvjo.mysql.rds.aliyuncs.com3306/

In [6]:
DATAPATH = '/root/autodl-tmp'



df_drop_duplicated = df[~df['id'].duplicated()]


df_drop_duplicated.to_csv(f'{DATAPATH}/150M_training_data.csv', index = False)

In [9]:
for col in ['occasion_cn', 'needs_cn', 'where_en','who_cn']:
    print(df_drop_duplicated[col].nunique())
    display(
        pd.DataFrame([
            df_drop_duplicated[col].value_counts(normalize = True),
            df_drop_duplicated[col].value_counts(),
        ]).T
    )

151

             proportion     count
occasion_cn
一人食光           0.195364  299350.0
一个人的屏幕时光       0.183639  281384.0
家庭聚会           0.150962  231314.0
家庭庆祝           0.087805  134541.0
宅家创意时刻         0.070134  107464.0
...                 ...       ...
在线购物/网购        0.000001       2.0
开学季/学生生活       0.000001       2.0
地摊经济           0.000001       2.0
企业聚会           0.000001       2.0
烘焙爱好者福利        0.000001       2.0

[151 rows x 2 columns]

150

           proportion     count
needs_cn
为了充饥         0.229331  351396.0
满足口腹欲        0.205615  315057.0
Others       0.126454  193761.0
健康养生         0.118757  181967.0
解腻           0.055943   85720.0
...               ...       ...
快速减肥/减脂      0.000001       2.0
高品质/高颜值      0.000001       2.0
适口性需求        0.000001       2.0
无糖健康/低卡需求    0.000001       2.0
艺术欣赏/文化需求    0.000001       2.0

[150 rows x 2 columns]

58

                        proportion     count
where_en
Home                      0.607246  930464.0
Unknown                   0.103544  158657.0
Others                    0.096106  147260.0
Office                    0.069435  106393.0
ShoppingMall              0.030664   46986.0
Home-Kitchen              0.026161   40086.0
Supermarket               0.015638   23961.0
Dormitory                 0.011873   18192.0
Restaurant                0.006781   10390.0
Campus                    0.006511    9976.0
TouristAttraction         0.004551    6973.0
NaturalScenery            0.003321    5088.0
Home-LivingRoom           0.002911    4461.0
Park                      0.001853    2840.0
Classroom                 0.001765    2705.0
PrivateCar                0.001535    2352.0
Camping/PicnicSpot        0.001169    1791.0
Long-distanceBus          0.000692    1061.0
Beach                     0.000644     987.0
Subway                    0.000617     945.0
Home-Bedroom              0.000595     912.0
Train/TrainStation        0.000581     890.0
Gym                       0.000569     872.0
Bar                       0.000519     795.0
Plane/Airport             0.000470     720.0
Home-Bed                  0.000433     664.0
ArtandExhibitionHall      0.000406     622.0
Hotel                     0.000394     603.0
LivePerformanceVenue      0.000356     545.0
Home-Sofa                 0.000321     492.0
HikingSpot                0.000321     492.0
Zoo/BotanicalGarden       0.000279     427.0
Cafe                      0.000240     367.0
Cinema                    0.000215     330.0
Resort                    0.000198     303.0
Library                   0.000187     287.0
Community                 0.000183     281.0
Bus                       0.000164     251.0
AmusementPark             0.000130     199.0
MeetingRoom               0.000110     169.0
KTV/Club                  0.000074     113.0
Stadium                   0.000071     109.0
BoardGameCafe             0.000039      60.0
Playground                0.000024      37.0
FishingSpot               0.000016      24.0
Massage/FootSpa           0.000013      20.0
OutdoorBasketballCourt    0.000013      20.0
CyclingRoute              0.000011      17.0
SkiResort                 0.000010      15.0
Online                    0.000010      15.0
SwimmingPool              0.000009      14.0
GolfCourse                0.000005       8.0
Outdoor                   0.000005       7.0
BotanicalGarden           0.000004       6.0
Street                    0.000004       6.0
HorseRanch                0.000003       4.0
ShuttleBus                0.000001       2.0
MahjongRoom               0.000001       2.0

35

        proportion     count
who_cn
其他        0.624615  957078.0
家人        0.106733  163544.0
Others    0.096026  147137.0
上班族       0.026432   40501.0
学生        0.022494   34467.0
朋友        0.020618   31593.0
女性        0.017746   27192.0
健身人士      0.012136   18596.0
养生人群      0.010304   15789.0
同事        0.009182   14069.0
追剧党       0.008976   13753.0
儿童        0.008270   12672.0
孕妇        0.007318   11213.0
创业者       0.004570    7002.0
追星族       0.004282    6561.0
情侣        0.004153    6364.0
宝妈        0.004127    6323.0
主妇        0.002894    4435.0
长辈        0.002080    3187.0
青年        0.001835    2811.0
单身        0.001526    2339.0
商务人士      0.001472    2256.0
中老年       0.001074    1645.0
夫妻        0.000546     836.0
运动爱好者     0.000256     392.0
男性        0.000167     256.0
宝爸        0.000110     169.0
公众人物      0.000015      23.0
家长        0.000012      19.0
烘焙爱好者     0.000011      17.0
父母        0.000005       8.0
青少年       0.000005       8.0
家庭        0.000004       6.0
亲子        0.000003       5.0
职场人士      0.000001       2.0

1995

In [1]:
OUTPUT_DIR = '/root/autodl-tmp/qwen2_05B_embeddings'

import os
from tqdm import tqdm
import pickle

embeding_idx = []
for filename in tqdm(os.listdir(OUTPUT_DIR)):
  with open(f'{OUTPUT_DIR}/{filename}', 'rb') as f:
    embeding_idx += list((pickle.load(f)).keys())

100%|██████████| 1995/1995 [30:18<00:00,  1.10it/s]

In [2]:
list(set(embeding_idx)).__len__()

19940574